### ISSUE TITLE
On clicking setting, It shows you cannot access this page

### ISSUE THREAD

**Issue by anantshah93** [lacicloud/payiota-woocommerce#2]
![screen shot 2017-12-09 at 1 24 48 pm](https://user-images.githubusercontent.com/13238619/33793794-5e50868e-dce4-11e7-996b-12ace8f67089.png)
It is redirecting to 

wp-admin/admin.php?page=wc-settings&tab=checkout

**Comment by lacicloud** [comment]
Hi!

@anantshah93 For some reason I was not notified of this issue. Is it still not working?

**Comment by lacicloud** [comment]
Closed due to lack of information. I emailed the reporter but received no reply. Will re-open on life sign.
